sequenceDiagram
  participant participant_createProjectReleaseHistoryRecord as createProjectReleaseHistoryRecord
  participant participant_createReleaseExecutionStateFromResult as createReleaseExecutionStateFromResult
  participant_createProjectReleaseHistoryRecord->>participant_createReleaseExecutionStateFromResult: createReleaseExecutionStateFromResult()
  participant_createReleaseExecutionStateFromResult-->>participant_createProjectReleaseHistoryRecord: return
